# Generated by Django 4.1.5 on 2023-01-15 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreriaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='libreriaApp.persona')),
                ('nacionalidad', models.CharField(max_length=200)),
            ],
            bases=('libreriaApp.persona',),
        ),
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='libreriaApp.persona')),
                ('estado', models.CharField(max_length=200)),
            ],
            bases=('libreriaApp.persona',),
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('editorial', models.CharField(max_length=200)),
                ('anio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateTimeField()),
                ('fecha_devolucion', models.DateTimeField()),
                ('multa', models.BooleanField()),
                ('id_lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreriaApp.lector')),
                ('id_libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreriaApp.libro')),
            ],
        ),
    ]
